baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[module.imports]]
path = "github.com/willfaught/paige"

[params.paige.list_page]
disable_authors = true
disable_date = true
disable_keywords = true
disable_reading_time = true
disable_series = true
disable_summary = true

[params.paige.page]
disable_authors = true
disable_date = true
disable_keywords = true
disable_next = true
disable_prev = true
disable_reading_time = true
disable_series = true
disable_toc = true